# Global Configurations
global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: "funless"

# Targets to scrape
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "funless"
    static_configs:
      - targets: ["fl-core-1:4000", "fl-worker-1:4021"]
