kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: funless-cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      fl: core
    extraPortMappings:
    - hostPort: 4000
      containerPort: 30210
  - role: worker
    labels:
      fl: worker
