apiVersion: v1
kind: Secret
metadata:
  name: fl-core-secret-kibana-password
  namespace: fl
type: Opaque
data:
  # the value is the base64 encoding of "kibanapassword"
  # this value __MUST__ be overwritten in production
  secret_key_password: aRgY7Odesha8qHfvRzWB # cannot set

