apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-elasticsearch
  namespace: fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-elasticsearch
  template:
    metadata:
      labels:
        app: fl-elasticsearch
    spec:
      serviceAccountName: fl-svc-account
      restartPolicy: "Always"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: fl
                operator: In
                values:
                - "core"
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "true"
