apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-kibana
  namespace: fl
  labels:
    app: fl-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-kibana
  template:
    metadata:
      labels:
        app: fl-kibana
    spec:
      serviceAccountName: fl-svc-account
      restartPolicy: "Always"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: fl
                operator: In
                values:
                - "core"
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.8.0
          ports:
            - containerPort: 5601
          env:
            - name: SERVERNAME
              value: kibana
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              value: elasticpassword
              # valueFrom:
              #   secretKeyRef:
              #     name: kibana-secrets
              #     key: kibana-password
          volumeMounts:
            - name: fl-kibana-data
              mountPath: /usr/share/kibana/data
      volumes:
        - name: fl-kibana-data
          # configMap:
            # name: fl-kibana-configmap
      hostNetwork: true

---

apiVersion: v1
kind: Service
metadata:
  name: fl-kibana
  namespace: fl
  labels:
    app: fl-kibana
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    app: fl-kibana
