apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-kibana
  namespace: fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-kibana
  template:
    metadata:
      labels:
        app: fl-kibana
    spec:
      serviceAccountName: fl-svc-account
      restartPolicy: "Always"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: fl
                operator: In
                values:
                - "core"
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.8.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS   
              value: "http://10-244-1-18.default.pod.cluster.local:9200" # set elastic ip
            - name: XPACK_SECURITY_ENABLED
              value: "true"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              value: "aRgY7Odesha8qHfvRzWB"
              # value: ${KIBANA_PASSWORD}
            - name: XPACK_REPORTING_ROLES_ENABLED
              value: "false"
            - name: XPACK_FLEET_REGISTRYURL
              value: "https://epr.elastic.co"
            - name: XPACK_FLEET_AGENTS_ENABLED
              value: "true"
            - name: xpack.encryptedSavedObjects.encryptionKey
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: fl-kibana
  namespace: fl
  labels:
    app: fl-kibana
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    app: fl-kibana


