kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: funless-cluster
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - hostPort: 4000
        containerPort: 4000
  - role: worker
