apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-prometheus
  namespace: fl
  labels:
    app: fl-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-prometheus
  template:
    metadata:
      labels:
        app: fl-prometheus
    spec:
      serviceAccountName: fl-svc-account
      restartPolicy: "Always"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: fl
                operator: In
                values:
                - "core"
      containers:
      - name: prometheus
        image: "giusdp/fl-prometheus:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: fl
  labels:
    app: fl-prometheus
spec:
  type: ClusterIP
  selector:
    app: fl-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP