apiVersion: v1
kind: ConfigMap
metadata:
  name: fl-prometheus-configmap
  namespace: fl
  labels:
    name: fl-prometheus-configmap
data:
  prometheus.yml: |-
    # Global Configurations
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

      external_labels:
        monitor: "funless"

    # Targets to scrape
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "funless"
        kubernetes_sd_configs:
          - role: "pod"
            namespaces:
              own_namespace: true