apiVersion: v1
kind: ServiceAccount
metadata:
  name: fl-svc-account
  namespace: fl

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fl-role
  namespace: fl
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fl-rolebinding
  namespace: fl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fl-role
subjects:
  - kind: ServiceAccount
    name: fl-svc-account