apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-elasticsearch
  namespace: fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-elasticsearch
  template:
    metadata:
      labels:
        app: fl-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
          env:
            - name: discovery.type
              value: single-node
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: ELASTIC_PASSWORD
              # value: ${ELASTIC_PASSWORD}
              value: elasticpassword
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: fl-elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
      volumes:
        - name: fl-elasticsearch-data

---
apiVersion: v1
kind: Service
metadata:
  name: fl-elasticsearch-service
  namespace: fl
spec:
  selector:
    app: fl-elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200


