apiVersion: v1
kind: Secret
metadata:
  name: fl-core-secret-key-base
  namespace: fl
type: Opaque
data:
  # the value is the base64 encoding of "agoodexampleofasecretkey"
  # this value __MUST__ be overwritten in production
  secret_key_base: YWdvb2RleGFtcGxlb2Zhc2VjcmV0a2V5Cg==