apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-elasticsearch
  namespace: fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-elasticsearch
  template:
    metadata:
      labels:
        app: fl-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.enrollment.enabled
              value: "false"
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
---

apiVersion: v1
kind: Service
metadata:
  name: fl-elasticsearch
  namespace: fl
  labels:
    app: fl-elasticsearch
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    app: fl-elasticsearch
