apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-elasticsearch
  namespace: fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-elasticsearch
  template:
    metadata:
      labels:
        app: fl-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_USERNAME
              value: "elastic"
              # value: ${ELASTIC_USER}
            - name: ELASTIC_PASSWORD
              value: "changeme"
              # value: ${ELASTIC_PASSWORD}
            - name: xpack.security.enabled
              value: "true"
      #     volumeMounts:
      #       - name: elasticsearch-mycerts
      #         mountPath: /usr/share/elasticsearch/config/mycerts
      #         readOnly: true
      # volumes:
      #   - name: elasticsearch-mycerts
      #     secret:
      #       secretName: elasticsearch-mycerts
      
