apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-kibana
  namespace: fl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-kibana
  template:
    metadata:
      labels:
        app: fl-kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.8.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://localhost:9200
          # readinessProbe:
          #   httpGet:
          #     path: /login
          #     port: 5601
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /login
          #     port: 5601
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          # # dependsOn:
          #   - name: fl-elasticsearch
          #     condition: Ready
---

apiVersion: v1
kind: Service
metadata:
  name: fl-kibana
  namespace: fl
  labels:
    app: fl-kibana
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    app: fl-kibana
